version: "3.9"

services:
  db:
    image: postgres:15
    container_name: lms_n105_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: lms_n105
    ports:
      - "5433:5432"
    volumes:
      - baza_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: lms_n105_app
    restart: always
    env_file:
      - .env
    ports:
      - "4000:3000"
    depends_on:
      - db
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate deploy &&
        npm run start:prod
      "
    environment:
      DATABASE_URL: postgres://postgres:12345@db:5432/lms_n105

volumes:
  baza_data: